name: Generate PDF List for GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - '**/*.pdf'

jobs:
  generate-pdf-list:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Generate PDF list JSON
        run: |
          mkdir -p public
          # Trova tutti i file PDF e crea una struttura JSON con il percorso completo
          find Documents -type f -name "*.pdf" | jq -R -s '
          split("\n") | map(select(length > 0)) |
          map({
            path: ., 
            name: (.|split("/"))[-1],
            folder: (.|split("/")[1:-1]|join("/"))
          })' > public/pdf_list.json

      - name: Push JSON to GitHub Pages
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add public/pdf_list.json
          git commit -m "Update PDF list"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
