permissions:
  contents: write
  actions: read

name: Generate and Publish PDF List

on:
  workflow_dispatch:

jobs:
  update-pdf-list:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the Byte-Your-Dreams/Documents repository
      - name: Check out Documents repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      # Clone source
      - name: Clone Source Repository
        run: |
          git clone https://github.com/Byte-Your-Dreams/Documents.git docs/
      
       # Copy folders from source
      # - name: Copy Folders
      #   run: |
      #    mkdir -p docs
      #    cp -r source-repo/* docs/

      # # Step 2: Generate the PDF list JSON file
      # - name: Generate PDF list JSON
      #   run: |
      #     mkdir -p public
      #     # Find all PDF files and generate a JSON file with full path information
      #     find Documents -type f -name "*.pdf" | jq -R -s '
      #     split("\n") | map(select(length > 0)) |
      #     map({
      #       path: ., 
      #       name: (.|split("/"))[-1],
      #       folder: (.|split("/")[1:-1]|join("/"))
      #     })' > public/pdf_list.json

      # # Step 3: Copy pdf_list.json to the site repository
      # - name: Copy JSON file to site repository
      #   run: |
      #     cp public/pdf_list.json site-repo/public/pdf_list.json

       # Step 5: Commit and push the JSON file to the site repository
      - name: Commit and Push JSON to Site Repository
        run: |
          cd docs
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Update PDF list automatically"
          git push