name: Generate PDF List

on:
  push:
    branches:
      - main
    paths:
      - '**/*.pdf'

jobs:
  generate-pdf-list:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Generate PDF list JSON
        run: |
          mkdir -p public
          find Documents -name "*.pdf" | jq -R -s 'split("\n") | map(select(length > 0)) | map({path: ., name: (.|split("/"))[-1]})' > public/pdf_list.json

      - name: Commit and push JSON file
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add public/pdf_list.json
          git commit -m "Update PDF list"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
